### ISSUE TITLE
Implement video streaming

### ISSUE THREAD

**Issue by jakedv24** [jakedv24/CrashRecorder-CPRE-458-558#2]
Be able to read raw video data from the Android device, save the video into some sort of buffer, that will be transferred to permanent storage once crash detection occurs.

**Comment by ibrotutic** [comment]
Have one record button, linked to VideoStreamViewModel that handles the data, default 1 minute worth of video?

**Comment by ibrotutic** [comment]
Start video thread and accelerometer thread on record button press.
